// flow-typed signature: 030b505205fbc9270cabfef8c4681608
// flow-typed version: <<STUB>>/eslint-config-anf_v^0.4.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-anf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-anf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-anf/base' {
  declare module.exports: any;
}

declare module 'eslint-config-anf/node' {
  declare module.exports: any;
}

declare module 'eslint-config-anf/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-anf/base.js' {
  declare module.exports: $Exports<'eslint-config-anf/base'>;
}
declare module 'eslint-config-anf/node.js' {
  declare module.exports: $Exports<'eslint-config-anf/node'>;
}
declare module 'eslint-config-anf/react.js' {
  declare module.exports: $Exports<'eslint-config-anf/react'>;
}
